name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B _builds

      - name: Build
        run: cmake --build _builds --target all

      - name: Test
        working-directory: _builds
        run: ctest -C Debug -V